// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjWL5v1iyc8Uz1fXLx0-5wygxmTaR0ZwE',
    appId: '1:418326688666:web:3358c5f4eb164ba9e9c023',
    messagingSenderId: '418326688666',
    projectId: 'newproject-45c48',
    authDomain: 'newproject-45c48.firebaseapp.com',
    storageBucket: 'newproject-45c48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqnF60b7qUrlb0KFdkariRmyXZfAX64cY',
    appId: '1:418326688666:android:193b6fbe0cae3cbfe9c023',
    messagingSenderId: '418326688666',
    projectId: 'newproject-45c48',
    storageBucket: 'newproject-45c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmtMOJW6XpkZIvC81NNzMdgo0YNhy2CX8',
    appId: '1:418326688666:ios:7da9c1da7117c060e9c023',
    messagingSenderId: '418326688666',
    projectId: 'newproject-45c48',
    storageBucket: 'newproject-45c48.appspot.com',
    iosBundleId: 'com.example.getapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmtMOJW6XpkZIvC81NNzMdgo0YNhy2CX8',
    appId: '1:418326688666:ios:0b7bb4e6ed5521f3e9c023',
    messagingSenderId: '418326688666',
    projectId: 'newproject-45c48',
    storageBucket: 'newproject-45c48.appspot.com',
    iosBundleId: 'com.example.getapi.RunnerTests',
  );
}
